bwd:
  build: bwd
  restart: always
  ports:
  - "50006:80"

#  - memory_limit=35000
  volumes_from:
  - bwd_home

iris2db:
  restart: always
  image: mariadb:5.5
  volumes_from:
  - bwd_data
  environment:
  - MYSQL_ROOT_PASSWORD=changeme
